### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-jfark#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by omid-web** [comment]
Fixed blank image issue

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/6645357/193427958-b72b5071-12a3-4733-a836-b22977701fc2.png">
